[programs.localnet]
lazycon = "6RUR6rTsMgSEpXqH25xXj3Qzdfd6MGRDe3P8hT949SsU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mayank/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
